<a href="https://colab.research.google.com/github/azizbekjb/azizbekjb/blob/main/Chapter_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Chapter 1.Vectros, matrices and arrays**

 1.1 Creating a Vector

*You need to create a vector*

In [7]:
#solution
#load library
import numpy as np

#create a vector as a row
vector_row = np.array({1, 2, 3})

#create a vector as column
vector_coloumn = np.array([
    [1],
    [2],
    [3]
])
print(f"vector row : {vector_row}")
print(f"vector column: {vector_coloumn}")

#result
  # vector row : {1, 2, 3}
  # vector column: [[1]
  #                 [2]
  #                 [3]]

vector row : {1, 2, 3}
vector column: [[1]
 [2]
 [3]]


1.2 Creating a Matrix

*You need to create a matrix*

In [9]:
#solution
#type 1
import numpy as np

#create a matrix
matrix = np.array([
    [1, 2],
    [1, 2],
    [1, 2]
])

print(matrix)
#result:
  # [[1 2]
  #  [1 2]
  #  [1 2]]

[[1 2]
 [1 2]
 [1 2]]


In [10]:
# solution
# type 2
import numpy as np

matrix = np.mat([
    [1, 2],
    [1, 2],
    [1, 2]
    ])
print(matrix)
# result:
# [[1 2]
#  [1 2]
#  [1 2]]

[[1 2]
 [1 2]
 [1 2]]


 1.3 Creating a Sparse Matrix

*Given data with very few nonzero values, you want to efficiently represent it*

In [17]:
#solution

#Load libraries
import numpy as np
from scipy import sparse

#Create a matrix
matrix = np.array([
    [0, 0],
    [0, 1],
    [3, 0]
])

# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

print(matrix_sparse)
# result:
  # (1, 1)	1
  #   (2, 0)	3

  (1, 1)	1
  (2, 0)	3


 1.4 Selecting Elements

*You need to select one or more elements in a vector or matrix*

In [25]:
#solution

#Load libraries
import numpy as np

# Create a vector as row
vector = np.array([1, 2, 3, 4, 5, 6])

# Create a matirx
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]
                   ])

#Select third element of vector
print(vector[2]) # 3

# Select second row, second column of matrix
print(matrix[1, 1]) # 5

# Select all elements of a vector
print(vector[:]) #[1 2 3 4 5 6]

# Select everything up to and including the third element
print(vector[:3]) # [1 2 3]

# Select everything after the third element
print(vector[3:]) # [4 5 6]

# Select the last element
print(vector[-1]) # 6

# Select the first  two rows and all columns of a matrix
print(matrix[:2, :]) #[[1 2 3]
                     #[4 5 6]]

# Select all rows and second columns
print(matrix[:, 1:2])
  # [[2]
  #  [5]
  #  [8]]
#Result:
# 3
# 5
# [1 2 3 4 5 6]
# [1 2 3]
# [4 5 6]
# 6
# [[1 2 3]
#  [4 5 6]]
# [[2]
#  [5]
#  [8]]

3
5
[1 2 3 4 5 6]
[1 2 3]
[4 5 6]
6
[[1 2 3]
 [4 5 6]]
[[2]
 [5]
 [8]]


1.5 Describing a Matrix

*You want to describe the shape, size, and dimensions of the matrix.*

In [31]:
#Solution

#Load library
import numpy as np

#Create a matrix
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Veiw number of rows and columns
print(matrix.shape) # (3, 4)

# View numbeof elements (rows * columns)
print(matrix.size) # 12

# View number of dimensions
print(matrix.ndim) #2
# Results:
# (3, 4)
# 12
# 2


(3, 4)
12
2


 1.6 Applying Operations to Elements

*Use NumPy's vectorize*

In [33]:
#Solution
#Load library
import numpy as np

# Create a matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Create function that adds 100 to something
add_100 = lambda i: i + 100

# Create vectorized function
vectrorized_add_100 = np.vectorize(add_100)

# Apply function to all elements in matrix
#type 1

print(vectrorized_add_100(matrix))
# array([[101, 102, 103],
#        [104, 105, 106],
#        [107, 108, 109]])

# type 2
matrix + 100
# array([[101, 102, 103],
#        [104, 105, 106],
#        [107, 108, 109]])

[[101 102 103]
 [104 105 106]
 [107 108 109]]


array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

1.7 Finding the Maximum and Minimum
 Values

You need to find the maximum or minimum value in an array.Use NumPy's max and min


In [39]:
# Solution
# type 1
import numpy as np

# Create matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
f"Maximum and minimum elemets in matrix: {np.max(matrix)} and {np.min(matrix)}"
#Maximum and minimum elements in matrix: 9 and 1

'Maximum and minimum elemets in matrix: 9 and 1'

In [41]:
# Solution
# type 2
import numpy as np

# Find maximum element in each column
np.max(matrix, axis=0) # array([7, 8, 9])

# Find maximum element in each row
np.max(matrix, axis=1) # array([3, 6, 9])

array([3, 6, 9])